repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: master
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.6