name: condax
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.6
  - click
  - requests
  - userpath
  - pyyaml
  # Test dependencies
  - pytest
  - coverage
  # Doc depe